export interface Breed {
  id: string
  name: string
  species: 'dog' | 'cat'
  origin: string
  size: 'small' | 'medium' | 'large'
  lifespan: string
  temperament: string[]
  description: string
  care_level: 'easy' | 'moderate' | 'high'
  exercise_needs: 'low' | 'moderate' | 'high'
  good_with_kids: boolean
  good_with_pets: boolean
  shedding: 'low' | 'moderate' | 'high'
  image_emoji: string
}

export const breeds: Breed[] = [
  // DOGS
  {
    id: 'labrador-retriever',
    name: 'Labrador Retriever',
    species: 'dog',
    origin: 'Canada',
    size: 'large',
    lifespan: '10–12 years',
    temperament: ['Friendly', 'Active', 'Outgoing', 'Gentle'],
    description: 'The Labrador Retriever is one of the most popular dog breeds in the world, known for its gentle nature and intelligence. Originally bred as a fishing and hunting companion, Labs excel as family pets, service dogs, and search-and-rescue animals.',
    care_level: 'easy',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐕',
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever',
    species: 'dog',
    origin: 'Scotland',
    size: 'large',
    lifespan: '10–12 years',
    temperament: ['Reliable', 'Trustworthy', 'Kind', 'Friendly', 'Confident'],
    description: 'Golden Retrievers are one of the most beloved family dogs, prized for their patient, friendly demeanor. They were originally bred as gun dogs to retrieve shot waterfowl and are now widely used as therapy and guide dogs.',
    care_level: 'easy',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐕',
  },
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    species: 'dog',
    origin: 'France',
    size: 'small',
    lifespan: '10–12 years',
    temperament: ['Affectionate', 'Playful', 'Adaptable', 'Alert'],
    description: 'French Bulldogs are compact, muscular dogs with a smooth coat and a friendly, easygoing personality. They thrive in both city apartments and country homes, making them one of the most versatile companion breeds.',
    care_level: 'moderate',
    exercise_needs: 'low',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐶',
  },
  {
    id: 'german-shepherd',
    name: 'German Shepherd',
    species: 'dog',
    origin: 'Germany',
    size: 'large',
    lifespan: '9–13 years',
    temperament: ['Intelligent', 'Loyal', 'Courageous', 'Obedient', 'Protective'],
    description: 'German Shepherds are highly intelligent working dogs known for their loyalty and versatility. They excel in police work, military service, search and rescue, and as loyal family companions with proper training.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: false,
    shedding: 'high',
    image_emoji: '🐕‍🦺',
  },
  {
    id: 'poodle',
    name: 'Poodle',
    species: 'dog',
    origin: 'Germany/France',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Intelligent', 'Active', 'Alert', 'Instinctual', 'Trainable'],
    description: 'Poodles are exceptionally intelligent dogs that come in three sizes: standard, miniature, and toy. They have a distinctive curly coat that is virtually non-shedding, making them popular with allergy sufferers.',
    care_level: 'high',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐩',
  },
  {
    id: 'bulldog',
    name: 'Bulldog',
    species: 'dog',
    origin: 'England',
    size: 'medium',
    lifespan: '8–10 years',
    temperament: ['Docile', 'Willful', 'Friendly', 'Gregarious'],
    description: 'Bulldogs are medium-sized dogs known for their loose, wrinkled skin and pushed-in nose. Despite their tough appearance, they are gentle, affectionate companions that bond strongly with their families.',
    care_level: 'moderate',
    exercise_needs: 'low',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐶',
  },
  {
    id: 'beagle',
    name: 'Beagle',
    species: 'dog',
    origin: 'England',
    size: 'small',
    lifespan: '12–15 years',
    temperament: ['Amiable', 'Curious', 'Determined', 'Merry', 'Excitable'],
    description: 'Beagles are small scent hounds that were originally bred for hunting rabbits. They are sturdy, compact dogs with an excellent nose and a cheerful, curious temperament that makes them wonderful family pets.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐕',
  },
  {
    id: 'rottweiler',
    name: 'Rottweiler',
    species: 'dog',
    origin: 'Germany',
    size: 'large',
    lifespan: '8–10 years',
    temperament: ['Loyal', 'Loving', 'Confident', 'Calm', 'Alert'],
    description: 'Rottweilers are powerful, loyal dogs with a calm and confident demeanor. When properly trained and socialized, they are gentle giants that are devoted to their families and make excellent guard dogs.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'moderate',
    image_emoji: '🐕',
  },
  {
    id: 'yorkshire-terrier',
    name: 'Yorkshire Terrier',
    species: 'dog',
    origin: 'England',
    size: 'small',
    lifespan: '13–16 years',
    temperament: ['Bold', 'Independent', 'Confident', 'Intelligent', 'Courageous'],
    description: 'Yorkshire Terriers, or "Yorkies," are tiny dogs with big personalities. Originally bred to catch rats in mines and mills, they are now beloved companions known for their long silky coats and spirited attitudes.',
    care_level: 'high',
    exercise_needs: 'moderate',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐶',
  },
  {
    id: 'dachshund',
    name: 'Dachshund',
    species: 'dog',
    origin: 'Germany',
    size: 'small',
    lifespan: '12–16 years',
    temperament: ['Playful', 'Curious', 'Devoted', 'Stubborn', 'Clever'],
    description: 'Dachshunds, nicknamed "wiener dogs," have a long body and short legs developed for hunting badgers underground. They come in two sizes and three coat types and are known for their bold, curious personalities.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🌭',
  },
  {
    id: 'siberian-husky',
    name: 'Siberian Husky',
    species: 'dog',
    origin: 'Siberia',
    size: 'medium',
    lifespan: '12–14 years',
    temperament: ['Outgoing', 'Friendly', 'Alert', 'Gentle', 'Intelligent'],
    description: 'Siberian Huskies are medium-sized working sled dogs known for their stunning appearance and wolflike features. They are friendly, outgoing dogs that love companionship but require extensive exercise to stay happy.',
    care_level: 'high',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐺',
  },
  {
    id: 'boxer',
    name: 'Boxer',
    species: 'dog',
    origin: 'Germany',
    size: 'medium',
    lifespan: '10–12 years',
    temperament: ['Playful', 'Energetic', 'Loyal', 'Intelligent', 'Friendly'],
    description: 'Boxers are athletic, energetic dogs that are playful and devoted to their families. They were originally bred in Germany as bull-baiting dogs and later as butchers\' helpers, but today they are wonderful family companions and guard dogs.',
    care_level: 'easy',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐕',
  },
  {
    id: 'great-dane',
    name: 'Great Dane',
    species: 'dog',
    origin: 'Germany',
    size: 'large',
    lifespan: '7–10 years',
    temperament: ['Friendly', 'Devoted', 'Gentle', 'Patient', 'Loving'],
    description: 'Great Danes are among the largest dog breeds in the world, yet they are known as "gentle giants" for their sweet, affectionate nature. Despite their imposing size, they are friendly and patient with children and other animals.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐕',
  },
  {
    id: 'doberman',
    name: 'Doberman',
    species: 'dog',
    origin: 'Germany',
    size: 'large',
    lifespan: '10–13 years',
    temperament: ['Energetic', 'Alert', 'Loyal', 'Obedient', 'Fearless'],
    description: 'Dobermans are sleek, powerful dogs known for their intelligence and loyalty. They were bred as personal protection dogs and are highly trainable, making them excellent working dogs for police and military roles.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐕',
  },
  {
    id: 'chihuahua',
    name: 'Chihuahua',
    species: 'dog',
    origin: 'Mexico',
    size: 'small',
    lifespan: '14–16 years',
    temperament: ['Devoted', 'Alert', 'Lively', 'Quick', 'Courageous'],
    description: 'Chihuahuas are the smallest recognized dog breed and one of the oldest breeds in the Americas. Despite their tiny size, they have bold, confident personalities and form intense bonds with their owners.',
    care_level: 'easy',
    exercise_needs: 'low',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐶',
  },
  {
    id: 'shih-tzu',
    name: 'Shih Tzu',
    species: 'dog',
    origin: 'China',
    size: 'small',
    lifespan: '10–16 years',
    temperament: ['Affectionate', 'Playful', 'Outgoing', 'Alert', 'Gentle'],
    description: 'Shih Tzus are small, sturdy dogs bred as companion animals for Chinese royalty. They have a flowing double coat and a sweet, trusting nature that makes them excellent companions for families and seniors alike.',
    care_level: 'high',
    exercise_needs: 'low',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐶',
  },
  {
    id: 'border-collie',
    name: 'Border Collie',
    species: 'dog',
    origin: 'Scotland/England',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Intelligent', 'Energetic', 'Responsive', 'Alert', 'Loyal'],
    description: 'Border Collies are considered the most intelligent dog breed in the world. Originally bred for herding livestock, they require intense mental and physical stimulation and excel in dog sports and obedience training.',
    care_level: 'high',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐕',
  },
  {
    id: 'australian-shepherd',
    name: 'Australian Shepherd',
    species: 'dog',
    origin: 'United States',
    size: 'medium',
    lifespan: '13–15 years',
    temperament: ['Intelligent', 'Active', 'Loyal', 'Protective', 'Versatile'],
    description: 'Australian Shepherds are highly energetic herding dogs developed in the western United States. They are exceptionally intelligent and need both physical activity and mental challenges to be happy and well-behaved.',
    care_level: 'high',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐕',
  },
  {
    id: 'pomeranian',
    name: 'Pomeranian',
    species: 'dog',
    origin: 'Germany/Poland',
    size: 'small',
    lifespan: '12–16 years',
    temperament: ['Playful', 'Bold', 'Inquisitive', 'Lively', 'Friendly'],
    description: 'Pomeranians are small spitz-type dogs known for their fluffy double coat and foxy face. Despite their tiny size, they are bold, energetic dogs that are alert and make surprisingly good watchdogs.',
    care_level: 'moderate',
    exercise_needs: 'low',
    good_with_kids: false,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐶',
  },
  {
    id: 'cavalier-king-charles',
    name: 'Cavalier King Charles Spaniel',
    species: 'dog',
    origin: 'England',
    size: 'small',
    lifespan: '12–15 years',
    temperament: ['Gentle', 'Affectionate', 'Patient', 'Playful', 'Adaptable'],
    description: 'Cavalier King Charles Spaniels are graceful, gentle dogs that were favorites of British nobility. They are extremely affectionate and adaptable, equally happy curled up on the sofa or out for a countryside walk.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐶',
  },
  {
    id: 'maltese',
    name: 'Maltese',
    species: 'dog',
    origin: 'Malta',
    size: 'small',
    lifespan: '12–15 years',
    temperament: ['Gentle', 'Playful', 'Affectionate', 'Fearless', 'Responsive'],
    description: 'Maltese are small, elegant dogs covered in long, silky white hair. One of the oldest toy breeds, they have been beloved companions for millennia. They are affectionate, gentle, and surprisingly fearless for their size.',
    care_level: 'high',
    exercise_needs: 'low',
    good_with_kids: false,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐶',
  },
  {
    id: 'cocker-spaniel',
    name: 'Cocker Spaniel',
    species: 'dog',
    origin: 'England',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Gentle', 'Smart', 'Happy', 'Adaptable', 'Merry'],
    description: 'Cocker Spaniels are cheerful, gentle dogs with silky, flowing coats. Originally bred as hunting dogs, they are now popular family companions known for their sweet expression and merry disposition.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐕',
  },
  {
    id: 'weimaraner',
    name: 'Weimaraner',
    species: 'dog',
    origin: 'Germany',
    size: 'large',
    lifespan: '11–14 years',
    temperament: ['Friendly', 'Fearless', 'Alert', 'Obedient', 'Energetic'],
    description: 'Weimaraners are sleek, silver-gray hunting dogs known as the "Grey Ghost." They were originally bred for hunting large game and are highly energetic dogs that need extensive daily exercise and mental stimulation.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐕',
  },
  {
    id: 'bernese-mountain',
    name: 'Bernese Mountain Dog',
    species: 'dog',
    origin: 'Switzerland',
    size: 'large',
    lifespan: '7–10 years',
    temperament: ['Affectionate', 'Loyal', 'Intelligent', 'Faithful', 'Gentle'],
    description: 'Bernese Mountain Dogs are large, sturdy working dogs from the Swiss Alps. They have a tricolor coat and a calm, affectionate nature. They are excellent family dogs but have a shorter lifespan than many breeds.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐕',
  },
  {
    id: 'vizsla',
    name: 'Vizsla',
    species: 'dog',
    origin: 'Hungary',
    size: 'medium',
    lifespan: '12–14 years',
    temperament: ['Affectionate', 'Loyal', 'Energetic', 'Gentle', 'Sensitive'],
    description: 'Vizslas are versatile Hungarian hunting dogs known for their golden-rust coat and affectionate nature. They form extremely close bonds with their owners and are sometimes called "velcro dogs" for their clinginess.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐕',
  },

  // CATS
  {
    id: 'maine-coon',
    name: 'Maine Coon',
    species: 'cat',
    origin: 'United States',
    size: 'large',
    lifespan: '12–15 years',
    temperament: ['Gentle', 'Playful', 'Adaptable', 'Friendly', 'Sociable'],
    description: 'Maine Coons are one of the largest domestic cat breeds, known for their thick, shaggy fur and tufted ears. They are often called "dog-like" cats for their friendly, playful nature and willingness to follow their owners around.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐱',
  },
  {
    id: 'ragdoll',
    name: 'Ragdoll',
    species: 'cat',
    origin: 'United States',
    size: 'large',
    lifespan: '13–18 years',
    temperament: ['Gentle', 'Calm', 'Affectionate', 'Docile', 'Easy-going'],
    description: 'Ragdolls are large, blue-eyed cats known for going limp like a ragdoll when picked up. They are extremely gentle, affectionate cats that love being held and are known for following their owners from room to room.',
    care_level: 'easy',
    exercise_needs: 'low',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'bengal',
    name: 'Bengal',
    species: 'cat',
    origin: 'United States',
    size: 'medium',
    lifespan: '12–16 years',
    temperament: ['Active', 'Curious', 'Energetic', 'Playful', 'Confident'],
    description: 'Bengals are a hybrid breed developed from Asian Leopard Cats, giving them a distinctive wild appearance with spots or marbling. They are highly active, intelligent cats that love to climb, play in water, and need lots of stimulation.',
    care_level: 'high',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐆',
  },
  {
    id: 'british-shorthair',
    name: 'British Shorthair',
    species: 'cat',
    origin: 'England',
    size: 'large',
    lifespan: '12–17 years',
    temperament: ['Calm', 'Patient', 'Adaptable', 'Loyal', 'Easygoing'],
    description: 'British Shorthairs are round-faced, plush-coated cats with a calm, easygoing temperament. They are independent yet affectionate, making them ideal for families and individuals who appreciate a low-maintenance companion.',
    care_level: 'easy',
    exercise_needs: 'low',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'persian',
    name: 'Persian',
    species: 'cat',
    origin: 'Iran',
    size: 'medium',
    lifespan: '12–17 years',
    temperament: ['Quiet', 'Gentle', 'Calm', 'Sweet', 'Affectionate'],
    description: 'Persians are elegant cats with long, flowing coats and flat faces. They are quiet, gentle cats that prefer calm environments and are happiest lounging in comfort. Their coat requires daily grooming to prevent matting.',
    care_level: 'high',
    exercise_needs: 'low',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'high',
    image_emoji: '🐱',
  },
  {
    id: 'siamese',
    name: 'Siamese',
    species: 'cat',
    origin: 'Thailand',
    size: 'medium',
    lifespan: '15–20 years',
    temperament: ['Social', 'Vocal', 'Intelligent', 'Affectionate', 'Demanding'],
    description: 'Siamese are one of the oldest and most recognizable cat breeds, known for their striking color-point coat and piercing blue eyes. They are extremely vocal, social cats that crave attention and conversation with their owners.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'scottish-fold',
    name: 'Scottish Fold',
    species: 'cat',
    origin: 'Scotland',
    size: 'medium',
    lifespan: '11–14 years',
    temperament: ['Sweet', 'Gentle', 'Adaptable', 'Quiet', 'Loyal'],
    description: 'Scottish Folds are known for their unique forward-folding ears that give them an owl-like appearance. They are gentle, sweet-natured cats that adapt well to different environments and form strong bonds with their families.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🦉',
  },
  {
    id: 'sphynx',
    name: 'Sphynx',
    species: 'cat',
    origin: 'Canada',
    size: 'medium',
    lifespan: '12–14 years',
    temperament: ['Energetic', 'Curious', 'Affectionate', 'Mischievous', 'Intelligent'],
    description: 'Sphynx cats are hairless cats known for their wrinkled skin, large ears, and extroverted personality. They are among the most affectionate cat breeds and love being the center of attention, often seeking warmth from their owners.',
    care_level: 'high',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '😸',
  },
  {
    id: 'russian-blue',
    name: 'Russian Blue',
    species: 'cat',
    origin: 'Russia',
    size: 'medium',
    lifespan: '15–20 years',
    temperament: ['Gentle', 'Reserved', 'Loyal', 'Quiet', 'Intelligent'],
    description: 'Russian Blues are elegant cats with a distinctive blue-gray coat and bright green eyes. They are reserved with strangers but deeply loyal to their families, following their favorite person around the house.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'norwegian-forest',
    name: 'Norwegian Forest Cat',
    species: 'cat',
    origin: 'Norway',
    size: 'large',
    lifespan: '14–16 years',
    temperament: ['Gentle', 'Adaptable', 'Independent', 'Friendly', 'Calm'],
    description: 'Norwegian Forest Cats are sturdy, large cats with a thick double coat adapted to cold climates. They are excellent climbers and hunters, but also gentle, adaptable companions that can coexist peacefully with families.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'high',
    image_emoji: '🐱',
  },
  {
    id: 'abyssinian',
    name: 'Abyssinian',
    species: 'cat',
    origin: 'Ethiopia',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Active', 'Curious', 'Playful', 'Independent', 'Intelligent'],
    description: 'Abyssinians are slender, athletic cats with a distinctive ticked coat. They are among the most active and playful cat breeds, constantly exploring their environment and learning new tricks. They thrive with interactive play.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'birman',
    name: 'Birman',
    species: 'cat',
    origin: 'Burma (Myanmar)',
    size: 'medium',
    lifespan: '12–16 years',
    temperament: ['Gentle', 'Affectionate', 'Curious', 'Social', 'Quiet'],
    description: 'Birmans are silky-coated cats with distinctive white "gloves" on their paws. Known as the "Sacred Cat of Burma," they are gentle, social cats that get along well with everyone and love being involved in family activities.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'oriental-shorthair',
    name: 'Oriental Shorthair',
    species: 'cat',
    origin: 'England',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Vocal', 'Active', 'Curious', 'Sociable', 'Intelligent'],
    description: 'Oriental Shorthairs are closely related to Siamese cats and share their vocal, social nature. They come in over 300 color combinations and are extremely active, playful cats that demand constant interaction.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'tonkinese',
    name: 'Tonkinese',
    species: 'cat',
    origin: 'Canada',
    size: 'medium',
    lifespan: '12–16 years',
    temperament: ['Playful', 'Sociable', 'Loving', 'Active', 'Curious'],
    description: 'Tonkinese are a cross between Siamese and Burmese cats, combining the best traits of both breeds. They are outgoing, playful cats that love human company and are known for being particularly chatty and affectionate.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'burmese',
    name: 'Burmese',
    species: 'cat',
    origin: 'Burma (Myanmar)',
    size: 'medium',
    lifespan: '16–18 years',
    temperament: ['Sociable', 'Curious', 'Playful', 'Affectionate', 'Vocal'],
    description: 'Burmese cats are compact, muscular cats with a satin-like coat. They are exceptionally sociable and often described as "dog-like" for their tendency to greet guests, play fetch, and follow their owners everywhere.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'devon-rex',
    name: 'Devon Rex',
    species: 'cat',
    origin: 'England',
    size: 'small',
    lifespan: '9–15 years',
    temperament: ['Mischievous', 'Playful', 'Curious', 'Energetic', 'Social'],
    description: 'Devon Rex cats are elfin-faced cats with large ears, wavy coats, and mischievous personalities. They are highly intelligent and playful cats that love perching on shoulders, retrieving toys, and learning tricks.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'turkish-angora',
    name: 'Turkish Angora',
    species: 'cat',
    origin: 'Turkey',
    size: 'medium',
    lifespan: '12–18 years',
    temperament: ['Playful', 'Affectionate', 'Intelligent', 'Energetic', 'Sociable'],
    description: 'Turkish Angoras are elegant cats with silky, long coats that are thought to have originated in Turkey. They are playful, intelligent cats that often seek out the highest point in a room and love interactive play.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'savannah',
    name: 'Savannah',
    species: 'cat',
    origin: 'United States',
    size: 'large',
    lifespan: '12–20 years',
    temperament: ['Active', 'Curious', 'Loyal', 'Adventurous', 'Confident'],
    description: 'Savannah cats are a hybrid between domestic cats and African servals, giving them a tall, slender body and spotted coat. They are highly active, adventurous cats that can be leash-trained and often behave more like dogs.',
    care_level: 'high',
    exercise_needs: 'high',
    good_with_kids: false,
    good_with_pets: false,
    shedding: 'low',
    image_emoji: '🐆',
  },
  {
    id: 'exotic-shorthair',
    name: 'Exotic Shorthair',
    species: 'cat',
    origin: 'United States',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Gentle', 'Calm', 'Playful', 'Affectionate', 'Quiet'],
    description: 'Exotic Shorthairs are often called the "lazy man\'s Persian" as they have all the Persian\'s gentle qualities with an easier-to-maintain short coat. They are calm, affectionate cats that adapt well to apartment living.',
    care_level: 'easy',
    exercise_needs: 'low',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'manx',
    name: 'Manx',
    species: 'cat',
    origin: 'Isle of Man',
    size: 'medium',
    lifespan: '12–14 years',
    temperament: ['Playful', 'Loyal', 'Social', 'Intelligent', 'Adaptable'],
    description: 'Manx cats are naturally tailless cats from the Isle of Man. They are sturdy, round cats with a rabbit-like hop and a playful, dog-like personality. They are highly loyal and often learn to fetch and come when called.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'chartreux',
    name: 'Chartreux',
    species: 'cat',
    origin: 'France',
    size: 'medium',
    lifespan: '12–15 years',
    temperament: ['Quiet', 'Attentive', 'Adaptable', 'Loyal', 'Gentle'],
    description: 'Chartreux are rare French cats known for their blue-gray coat and copper-orange eyes. They are quiet, observant cats that rarely vocalize but communicate through chirps and trills. They are loyal companions that bond closely with one person.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'balinese',
    name: 'Balinese',
    species: 'cat',
    origin: 'United States',
    size: 'medium',
    lifespan: '12–18 years',
    temperament: ['Vocal', 'Intelligent', 'Playful', 'Sociable', 'Affectionate'],
    description: 'Balinese cats are essentially long-haired Siamese with a silky, flowing coat. They share the Siamese\'s vocal, extroverted personality and are highly intelligent cats that thrive on interaction and mental stimulation.',
    care_level: 'moderate',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
  {
    id: 'bombay',
    name: 'Bombay',
    species: 'cat',
    origin: 'United States',
    size: 'medium',
    lifespan: '12–16 years',
    temperament: ['Affectionate', 'Playful', 'Curious', 'Sociable', 'Gentle'],
    description: 'Bombay cats were developed to resemble a miniature black panther. They have a sleek black coat and copper eyes and are among the most affectionate cat breeds, often choosing to sleep curled up with their owners.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'cornish-rex',
    name: 'Cornish Rex',
    species: 'cat',
    origin: 'England',
    size: 'small',
    lifespan: '11–15 years',
    temperament: ['Active', 'Curious', 'Playful', 'Sociable', 'Affectionate'],
    description: 'Cornish Rex cats have a distinctive soft, wavy coat caused by a genetic mutation. They are slender, elegant cats with large ears and eyes, known for staying kitten-like and playful well into old age.',
    care_level: 'moderate',
    exercise_needs: 'high',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'low',
    image_emoji: '🐱',
  },
  {
    id: 'american-shorthair',
    name: 'American Shorthair',
    species: 'cat',
    origin: 'United States',
    size: 'medium',
    lifespan: '15–20 years',
    temperament: ['Easy-going', 'Adaptable', 'Playful', 'Gentle', 'Independent'],
    description: 'American Shorthairs are the native working cats of North America, descended from cats brought over on the Mayflower. They are healthy, adaptable cats with a gentle temperament and minimal grooming requirements.',
    care_level: 'easy',
    exercise_needs: 'moderate',
    good_with_kids: true,
    good_with_pets: true,
    shedding: 'moderate',
    image_emoji: '🐱',
  },
]
